INSERT INTO users (id, first_name, last_name, email, password, created_at, updated_at) VALUES
  (gen_random_uuid(), 'Jan',       'Kowalski',  'jan.kowalski@example.com',  '$2a$10$EXAMPLEHASHEDPASS1', NOW(), NOW()),
  (gen_random_uuid(), 'Anna',      'Nowak',     'anna.nowak@example.com',     '$2a$10$EXAMPLEHASHEDPASS2', NOW(), NOW()),
  (gen_random_uuid(), 'Piotr',     'Wiśniewski','piotr.wisniewski@example.com','$2a$10$EXAMPLEHASHEDPASS3', NOW(), NOW()),
  (gen_random_uuid(), 'Katarzyna', 'Wójcik',    'katarzyna.wojcik@example.com','$2a$10$EXAMPLEHASHEDPASS4', NOW(), NOW()),
  (gen_random_uuid(), 'Tomasz',    'Kamiński',  'tomasz.kaminski@example.com','$2a$10$EXAMPLEHASHEDPASS5', NOW(), NOW()),
  (gen_random_uuid(), 'Magdalena', 'Lewandowska','magdalena.lewandowska@example.com','$2a$10$EXAMPLEHASHEDPASS6', NOW(), NOW()),
  (gen_random_uuid(), 'Michał',    'Zieliński', 'michal.zielinski@example.com','$2a$10$EXAMPLEHASHEDPASS7', NOW(), NOW()),
  (gen_random_uuid(), 'Agnieszka', 'Szymańska', 'agnieszka.szymanska@example.com','$2a$10$EXAMPLEHASHEDPASS8', NOW(), NOW()),
  (gen_random_uuid(), 'Paweł',     'Dąbrowski', 'pawel.dabrowski@example.com','$2a$10$EXAMPLEHASHEDPASS9', NOW(), NOW()),
  (gen_random_uuid(), 'Barbara',   'Kozłowska', 'barbara.kozlowska@example.com','$2a$10$EXAMPLEHASHEDPASS10', NOW(), NOW()),
  (gen_random_uuid(), 'Krzysztof', 'Jankowski', 'krzysztof.jankowski@example.com','$2a$10$EXAMPLEHASHEDPASS11', NOW(), NOW()),
  (gen_random_uuid(), 'Ewa',       'Mazur',     'ewa.mazur@example.com',     '$2a$10$EXAMPLEHASHEDPASS12', NOW(), NOW()),
  (gen_random_uuid(), 'Adam',      'Krawczyk',  'adam.krawczyk@example.com', '$2a$10$EXAMPLEHASHEDPASS13', NOW(), NOW()),
  (gen_random_uuid(), 'Elżbieta',  'Piotrowska','elzbieta.piotrowska@example.com','$2a$10$EXAMPLEHASHEDPASS14', NOW(), NOW()),
  (gen_random_uuid(), 'Robert',    'Grabowski', 'robert.grabowski@example.com','$2a$10$EXAMPLEHASHEDPASS15', NOW(), NOW()),
  (gen_random_uuid(), 'Joanna',    'Nowicka',   'joanna.nowicka@example.com','$2a$10$EXAMPLEHASHEDPASS16', NOW(), NOW()),
  (gen_random_uuid(), 'Andrzej',   'Pawlak',    'andrzej.pawlak@example.com','$2a$10$EXAMPLEHASHEDPASS17', NOW(), NOW()),
  (gen_random_uuid(), 'Aleksandra','Michalska', 'aleksandra.michalska@example.com','$2a$10$EXAMPLEHASHEDPASS18', NOW(), NOW()),
  (gen_random_uuid(), 'Łukasz',    'Król',      'lukasz.krol@example.com',  '$2a$10$EXAMPLEHASHEDPASS19', NOW(), NOW()),
  (gen_random_uuid(), 'Małgorzata','Wieczorek', 'malgorzata.wieczorek@example.com','$2a$10$EXAMPLEHASHEDPASS20', NOW(), NOW());
